### ISSUE TITLE
Building failed! Patching of EP_MBEDTLS

### ISSUE THREAD

**Issue by dsibold** [BSI-Bund/TaSK#11] opened 2023-03-09 17:20 UTC
patching file 'include/mbedtls/config.h'
patching file 'include/mbedtls/ssl.h'
patching file 'library/ssl_cli.c'
patching file 'include/mbedtls/ssl.h'
patching file 'library/ssl_cli.c'
patching file 'library/debug.c'
patching file 'library/ssl_cli.c'
patching file 'library/ssl_cli.c'
patching file 'include/mbedtls/ssl.h'
1 out of 1 hunks failed--saving rejects to 'include/mbedtls/ssl.h.rej'
patching file 'library/ssl_cli.c'
patching file 'library/ssl_srv.c'
patching file 'library/ssl_tls.c'
make[2]: *** [EP_MBEDTLS-prefix/src/EP_MBEDTLS-stamp/EP_MBEDTLS-patch] Error 1
make[1]: *** [CMakeFiles/EP_MBEDTLS.dir/all] Error 2
make: *** [all] Error 2

OS: macOS 13.2.1
cmake 3.25.3

**Comment by rk8129406** [comment] 2023-06-14 11:49
Duplicate of #3 
At the moment, we do not support MacOS.

**Comment by rk8129406** [comment] 2023-06-14 11:50
Duplicate of #3
At the moment, we do not support MacOS.

**Closed by rk8129406** 2023-06-14 11:50 UTC
